# Generated by Django 4.1.7 on 2023-03-25 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='user',
        ),
    ]
